#!/bin/bash

set -e
TAG=$(date +%Y%m%d)

for DIST in precise trusty vivid; do
  docker build -t debuild/${DIST}:${TAG} debuild/${DIST}
  docker tag -f debuild/${DIST}:${TAG} debuild/${DIST}:latest
  ./docs debuild/${DIST}
done

for DIST in centos{5,6,7}; do
  docker build -t rpmbuild/${DIST}:${TAG} rpmbuild/${DIST}
  docker tag -f rpmbuild/${DIST}:${TAG} rpmbuild/${DIST}:latest
  ./docs rpmbuild/${DIST}
done
