#!/bin/bash
set -eu

ROOT=${1:-}
if [[ -z ${ROOT} ]]; then
  find . -name 'Dockerfile' | sed -e 's,/Dockerfile,,' | xargs -n1 $0
  exit $?
fi

if [[ ! -d ${ROOT} ]]; then
  echo >&2 "${ROOT}: Not found"
  exit 1
fi

if [[ ! -f ${ROOT}/README ]]; then
  echo >&2 "${ROOT}: No README found"
  exit 1
fi

if [[ ! -f ${ROOT}/Dockerfile ]]; then
  echo >&2 "${ROOT}: No Dockerfile found"
  exit 1
fi

(
  sed -e '/<DOCKERFILE>/d'                      ${ROOT}/README
  sed -e '/^MAINTAINER /d;s/^/    /;s/^    $//' ${ROOT}/Dockerfile
) > ${ROOT}/README.md
