#!/bin/bash

set -e
TAG=$(date +%Y%m%d)

for TAG in "$@"; do
  for DIST in precise trusty vivid; do
    docker push debuild/${DIST}:${TAG}
  done

  for DIST in centos{5,6,7}; do
    docker push rpmbuild/${DIST}:${TAG}
  done
done
